In [1]:
import pandas as pd
import numpy as np

In [2]:
data_path = 'C:/Users/smartgrid_AI/Documents/kms/Python_Study/3. World Energy Consumption.csv'
dat_source = pd.read_csv(data_path)
dat_source = pd.DataFrame(dat_source)
#dat_s = np.array(dat_source, dtype='float')

In [3]:
dat_source

iso_code      country  year  coal_prod_change_pct  coal_prod_change_twh  \
0          AFG  Afghanistan  1900                   NaN                   NaN   
1          AFG  Afghanistan  1901                   NaN                 0.000   
2          AFG  Afghanistan  1902                   NaN                 0.000   
3          AFG  Afghanistan  1903                   NaN                 0.000   
4          AFG  Afghanistan  1904                   NaN                 0.000   
...        ...          ...   ...                   ...                   ...   
17427      ZWE     Zimbabwe  2015               -25.013               -10.847   
17428      ZWE     Zimbabwe  2016               -37.694               -12.257   
17429      ZWE     Zimbabwe  2017                 8.375                 1.697   
17430      ZWE     Zimbabwe  2018                22.555                 4.952   
17431      ZWE     Zimbabwe  2019               -35.015                -9.422   

       gas_prod_change_pct  gas_prod_change_twh  oil_prod_change_pct  \
0                      NaN                  NaN                  NaN   
1                      NaN                  NaN                  NaN   
2                      NaN                  NaN                  NaN   
3                      NaN                  NaN                  NaN   
4                      NaN                  NaN                  NaN   
...                    ...                  ...                  ...   
17427                  NaN                  NaN                  NaN   
17428                  NaN                  NaN                  NaN   
17429                  NaN                  NaN                  NaN   
17430                  NaN                  NaN                  NaN   
17431                  NaN                  NaN                  NaN   

       oil_prod_change_twh  energy_cons_change_pct  ...  \
0                      NaN                     NaN  ...   
1                      NaN                     NaN  ...   
2                      NaN                     NaN  ...   
3                      NaN                     NaN  ...   
4                      NaN                     NaN  ...   
...                    ...                     ...  ...   
17427                  NaN                  -0.789  ...   
17428                  NaN                 -14.633  ...   
17429                  NaN                     NaN  ...   
17430                  NaN                     NaN  ...   
17431                  NaN                     NaN  ...   

       solar_elec_per_capita  solar_energy_per_capita           gdp  \
0                        NaN                      NaN           NaN   
1                        NaN                      NaN           NaN   
2                        NaN                      NaN           NaN   
3                        NaN                      NaN           NaN   
4                        NaN                      NaN           NaN   
...                      ...                      ...           ...   
17427                  0.579                      NaN  2.503057e+10   
17428                  0.641                      NaN  2.515176e+10   
17429                  0.773                      NaN           NaN   
17430                  0.970                      NaN           NaN   
17431                  0.956                      NaN           NaN   

       wind_share_elec  wind_cons_change_pct  wind_share_energy  \
0                  NaN                   NaN                NaN   
1                  NaN                   NaN                NaN   
2                  NaN                   NaN                NaN   
3                  NaN                   NaN                NaN   
4                  NaN                   NaN                NaN   
...                ...                   ...                ...   
17427              0.0                   NaN                NaN   
17428              0.0                   NaN                NaN   
174

In [4]:
dat_name = dat_source.iloc[:,0:3]
dat_val = dat_source.iloc[:,28:40]

In [5]:
dat_val

electricity_generation  biofuel_electricity  coal_electricity  \
0                         NaN                  NaN               NaN   
1                         NaN                  NaN               NaN   
2                         NaN                  NaN               NaN   
3                         NaN                  NaN               NaN   
4                         NaN                  NaN               NaN   
...                       ...                  ...               ...   
17427                   9.388                0.128             4.312   
17428                   6.826                0.147             3.715   
17429                   7.310                0.151             3.219   
17430                   9.133                0.187             3.932   
17431                   9.046                0.207             3.805   

       fossil_electricity  gas_electricity  hydro_electricity  \
0                     NaN              NaN                NaN   
1                     NaN              NaN                NaN   
2                     NaN              NaN                NaN   
3                     NaN              NaN                NaN   
4                     NaN              NaN                NaN   
...                   ...              ...                ...   
17427               4.312              0.0              4.940   
17428               3.715              0.0              2.955   
17429               3.219              0.0              3.929   
17430               3.932              0.0              5.000   
17431               3.805              0.0              5.020   

       nuclear_electricity  oil_electricity  other_renewable_electricity  \
0                      NaN              NaN                          NaN   
1                      NaN              NaN                          NaN   
2                      NaN              NaN                          NaN   
3                      NaN              NaN                          NaN   
4                      NaN              NaN                          NaN   
...                    ...              ...                          ...   
17427                  0.0              0.0                        0.128   
17428                  0.0              0.0                        0.147   
17429                  0.0              0.0                        0.151   
17430                  0.0              0.0                        0.187   
17431                  0.0              0.0                        0.207   

       other_renewable_exc_biofuel_electricity  renewables_electricity  \
0                                          NaN                     NaN   
1                                          NaN                     NaN   
2                                          NaN                     NaN   
3                                          NaN                     NaN   
4                                          NaN                     NaN   
...                                        ...                     ...   
17427                                      0.0                   5.076   
17428                                      0.0                   3.111   
17429                                      0.0                   4.091   
17430                                      0.0                   5.201   
17431                                      0.0                   5.241   

       solar_electricity  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
...                  ...  
17427              0.008  
17428              0.009  
17429              0.011  
17430              0.014  
17431              0.014  

[17432 rows x 12 columns]

In [6]:
dat = pd.concat([dat_name, dat_val], axis=1)

In [7]:
dat

iso_code      country  year  electricity_generation  \
0          AFG  Afghanistan  1900                     NaN   
1          AFG  Afghanistan  1901                     NaN   
2          AFG  Afghanistan  1902                     NaN   
3          AFG  Afghanistan  1903                     NaN   
4          AFG  Afghanistan  1904                     NaN   
...        ...          ...   ...                     ...   
17427      ZWE     Zimbabwe  2015                   9.388   
17428      ZWE     Zimbabwe  2016                   6.826   
17429      ZWE     Zimbabwe  2017                   7.310   
17430      ZWE     Zimbabwe  2018                   9.133   
17431      ZWE     Zimbabwe  2019                   9.046   

       biofuel_electricity  coal_electricity  fossil_electricity  \
0                      NaN               NaN                 NaN   
1                      NaN               NaN                 NaN   
2                      NaN               NaN                 NaN   
3                      NaN               NaN                 NaN   
4                      NaN               NaN                 NaN   
...                    ...               ...                 ...   
17427                0.128             4.312               4.312   
17428                0.147             3.715               3.715   
17429                0.151             3.219               3.219   
17430                0.187             3.932               3.932   
17431                0.207             3.805               3.805   

       gas_electricity  hydro_electricity  nuclear_electricity  \
0                  NaN                NaN                  NaN   
1                  NaN                NaN                  NaN   
2                  NaN                NaN                  NaN   
3                  NaN                NaN                  NaN   
4                  NaN                NaN                  NaN   
...                ...                ...                  ...   
17427              0.0              4.940                  0.0   
17428              0.0              2.955                  0.0   
17429              0.0              3.929                  0.0   
17430              0.0              5.000                  0.0   
17431              0.0              5.020                  0.0   

       oil_electricity  other_renewable_electricity  \
0                  NaN                          NaN   
1                  NaN                          NaN   
2                  NaN                          NaN   
3                  NaN                          NaN   
4                  NaN                          NaN   
...                ...                          ...   
17427              0.0                        0.128   
17428              0.0                        0.147   
17429              0.0                        0.151   
17430              0.0                        0.187   
17431              0.0                        0.207   

       other_renewable_exc_biofuel_electricity  renewables_electricity  \
0                                          NaN                     NaN   
1                                          NaN                     NaN   
2                                          NaN                     NaN   
3                                          NaN                     NaN   
4                                          NaN                     NaN   
...                                        ...                     ...   
17427                                      0.0                   5.076   
17428                                      0.0                   3.111   
17429                                      0.0                   4.091   
17430                                      0.0                   5.201   
17431                                      0.0                   5.241   

       solar_electricity  
0                    NaN  
1                    NaN  
2                    NaN  
3    

In [8]:
dat.shape, dat.shape[0]

((17432, 15), 17432)

In [9]:
dat_source["population"]

0         5021241.0
1         5053439.0
2         5085403.0
3         5118005.0
4         5150814.0
            ...    
17427    13815000.0
17428    14030000.0
17429    14237000.0
17430    14439000.0
17431    14645000.0
Name: population, Length: 17432, dtype: float64

In [10]:
dat_chn = np.zeros((15))
dat_pop = np.zeros(1)
for i in range(dat.shape[0]):
    if dat.iloc[i,0] == 'CHN' or dat.iloc[i,0] == 'DEU' or dat.iloc[i,0] == 'ITA' or dat.iloc[i,0] == 'JPN' or dat.iloc[i,0] == 'KOR' or dat.iloc[i,0] == 'USA':
        #print(dat.iloc[i,0])
        dat_chn = np.concatenate([dat_chn.reshape(-1,15), np.array(dat.iloc[i,:]).reshape(-1,15)])
        dat_pop = np.concatenate([dat_pop, np.array(dat_source["population"].iloc[i]).reshape(-1)])

In [11]:
dat_chn.shape, dat_pop.shape

((727, 15), (727,))

In [12]:
dat_new = dat_chn.reshape(-1,15)
dat_pop = dat_pop.reshape(-1,1)

In [13]:
dat_new

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['CHN', 'China', 1900, ..., nan, nan, nan],
       ['CHN', 'China', 1901, ..., nan, nan, nan],
       ...,
       ['USA', 'United States', 2018, ..., 15.967, 730.502, 93.365],
       ['USA', 'United States', 2019, ..., 15.472999999999999, 757.393,
        106.89399999999999],
       ['USA', 'United States', 2020, ..., 16.93, 827.938, 132.63]],
      dtype=object)

In [14]:
dat_new2 = np.concatenate([dat_new, dat_pop],axis=1)

In [15]:
dat_new2

array([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ['CHN', 'China', 1900, ..., nan, nan, 400774176.0],
       ['CHN', 'China', 1901, ..., nan, nan, 402934752.0],
       ...,
       ['USA', 'United States', 2018, ..., 730.502, 93.365, 327096000.0],
       ['USA', 'United States', 2019, ..., 757.393, 106.89399999999999,
        329064992.0],
       ['USA', 'United States', 2020, ..., 827.938, 132.63, nan]],
      dtype=object)

In [16]:
df = pd.DataFrame(dat_new2[1:,:])
df

0              1     2        3       4        5        6        7   \
0    CHN          China  1900      NaN     NaN      NaN      NaN      NaN   
1    CHN          China  1901      NaN     NaN      NaN      NaN      NaN   
2    CHN          China  1902      NaN     NaN      NaN      NaN      NaN   
3    CHN          China  1903      NaN     NaN      NaN      NaN      NaN   
4    CHN          China  1904      NaN     NaN      NaN      NaN      NaN   
..   ...            ...   ...      ...     ...      ...      ...      ...   
721  USA  United States  2016  4095.49   62.76  1239.15  2668.22  1391.11   
722  USA  United States  2017  4058.26  62.762  1205.84   2549.2  1308.88   
723  USA  United States  2018  4203.94  61.901  1145.96  2666.35  1482.19   
724  USA  United States  2019  4161.83  57.507  964.957  2595.03   1598.3   
725  USA  United States  2020  4049.85  56.055  773.806  2431.99  1629.24   

          8        9       10      11      12       13       14           15  
0        NaN      NaN     NaN     NaN     NaN      NaN      NaN  4.00774e+08  
1        NaN      NaN     NaN     NaN     NaN      NaN      NaN  4.02935e+08  
2        NaN      NaN     NaN     NaN     NaN      NaN      NaN  4.05061e+08  
3        NaN      NaN     NaN     NaN     NaN      NaN      NaN  4.07294e+08  
4        NaN      NaN     NaN     NaN     NaN      NaN      NaN  4.09563e+08  
..       ...      ...     ...     ...     ...      ...      ...          ...  
721  261.126  805.694  37.959  78.586  15.826  621.571   54.866  3.23016e+08  
722  293.839   804.95  34.486  78.688  15.927  704.106   77.276  3.25085e+08  
723  286.619  807.084  38.199  77.868  15.967  730.502   93.365  3.27096e+08  
724  282.613  809.409  31.772   72.98  15.473  757.393  106.894  3.29065e+08  
725   285.79  789.919  28.947  72.985   16.93  827.938   132.63          NaN  

[726 rows x 16 columns]

In [17]:
df=df.fillna(0) #df.replace(np.NaN,0)
df

0              1     2         3       4         5         6         7   \
0    CHN          China  1900     0.000   0.000     0.000     0.000     0.000   
1    CHN          China  1901     0.000   0.000     0.000     0.000     0.000   
2    CHN          China  1902     0.000   0.000     0.000     0.000     0.000   
3    CHN          China  1903     0.000   0.000     0.000     0.000     0.000   
4    CHN          China  1904     0.000   0.000     0.000     0.000     0.000   
..   ...            ...   ...       ...     ...       ...       ...       ...   
721  USA  United States  2016  4095.487  62.760  1239.149  2668.222  1391.114   
722  USA  United States  2017  4058.261  62.762  1205.835  2549.205  1308.884   
723  USA  United States  2018  4203.937  61.901  1145.962  2666.350  1482.189   
724  USA  United States  2019  4161.834  57.507   964.957  2595.032  1598.303   
725  USA  United States  2020  4049.847  56.055   773.806  2431.990  1629.237   

          8        9       10      11      12       13       14           15  
0      0.000    0.000   0.000   0.000   0.000    0.000    0.000  400774176.0  
1      0.000    0.000   0.000   0.000   0.000    0.000    0.000  402934752.0  
2      0.000    0.000   0.000   0.000   0.000    0.000    0.000  405061184.0  
3      0.000    0.000   0.000   0.000   0.000    0.000    0.000  407294080.0  
4      0.000    0.000   0.000   0.000   0.000    0.000    0.000  409562848.0  
..       ...      ...     ...     ...     ...      ...      ...          ...  
721  261.126  805.694  37.959  78.586  15.826  621.571   54.866  323016000.0  
722  293.839  804.950  34.486  78.688  15.927  704.106   77.276  325084992.0  
723  286.619  807.084  38.199  77.868  15.967  730.502   93.365  327096000.0  
724  282.613  809.409  31.772  72.980  15.473  757.393  106.894  329064992.0  
725  285.790  789.919  28.947  72.985  16.930  827.938  132.630          0.0  

[726 rows x 16 columns]

In [18]:
def myfun(x):
    y = []
    for i in range(max(x.shape)):
        if x.iloc[i,0] == 'CHN' or x.iloc[i,0] == 'JPN' or x.iloc[i,0] == 'KOR':
            if x.iloc[i,15]!=0:
                if i==0:
                    y2 = np.array(sum(x.iloc[i,4:14])/x.iloc[i,15])
                else:
                    y2 = np.concatenate([y2.reshape(-1,1), np.array(sum(x.iloc[i,4:14])/x.iloc[i,15]).reshape(-1,1)])
            else:
                if i==0:
                    y2 = np.NaN
                else:
                    y2 = np.concatenate([y2.reshape(-1,1), np.array(np.NaN).reshape(-1,1)])
    y2 = np.array(y2)
    return y2

In [19]:
result = myfun(df)

In [20]:
result = result.reshape(3,-1)
result

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000

In [21]:
result2 = result[:,-28:]

In [22]:
result2

array([[1.33027187e-06, 1.49627246e-06, 1.61219132e-06, 1.71629216e-06,
        1.78801592e-06, 1.82355260e-06, 1.92206567e-06, 2.03330587e-06,
        2.24221597e-06, 2.48182956e-06, 2.79546263e-06, 3.23110671e-06,
        3.60161648e-06, 4.11305376e-06, 4.74591126e-06, 5.02014369e-06,
        5.33648568e-06, 6.09500139e-06, 6.75649342e-06, 7.07997245e-06,
        7.56151195e-06, 7.81669163e-06, 7.91663350e-06, 8.19667480e-06,
        8.66306110e-06, 9.28001860e-06, 9.61599333e-06,            nan],
       [1.25585846e-05, 1.33936915e-05, 1.35321173e-05, 1.37285304e-05,
        1.38740514e-05, 1.38934997e-05, 1.42714214e-05, 1.38100671e-05,
        1.35312025e-05, 1.39746741e-05, 1.42401880e-05, 1.43342797e-05,
        1.44265231e-05, 1.46090031e-05, 1.54339269e-05, 1.44379682e-05,
        1.38068764e-05, 1.54557888e-05, 1.63361505e-05, 1.63291519e-05,
        1.64921443e-05, 1.60917304e-05, 1.56737274e-05, 1.55483278e-05,
        1.54943884e-05, 1.51107608e-05, 1.43362131e-05,        

In [23]:
from myfunc import *

In [28]:
mod1 = adding(df).reshape(3,-1)
mod2 = addanddivide(df).reshape(3,-1)

In [29]:
mod1, mod2

(array([[    0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0.   ,     0.   ,     0.   ,     0.   ,     0.   ,
             0.   ,     0